version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: bookstore
    ports:
    - "5432:5432"
  mongoDB:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookstore